name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: vx.x.x

    - name: Verify formatting
      run: deno fmt --check

    - name: Run linter
      run: deno lint

    - name: Build CLI
      run: deno task build

    - name: Run tests
      run: deno test --allow-read --allow-run --allow-write tests/

    - name: Check build artifacts
      run: |
        ls -la bin/
        file bin/md2jsx